version: '3.8'

services:
  db:
    image: sha256:ac8895c27031112a71ca92e662d8dcdbf114cdc3aa5bcc51900c32d5a50102ca
    container_name: book_store_bd
    environment:
      POSTGRES_USER: 'fakedpassword'
      POSTGRES_PASSWORD: 'dev_book_store_admin'
    networks:
      - my_network

  app:
    image: sha256:7bf9f25de554a985ee643bce849347871d0d69f4c2870f370beaaf9997335655
    container_name: book_store_back
    ports:
      - "5001:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dev_book_store_db
      SPRING_DATASOURCE_USERNAME: dev_book_store_admin
      SPRING_DATASOURCE_PASSWORD: fakedPassword
    networks:
      - my_network

#  frontend:
#    image: sha256:c062d11a3f7137ae2088da7517bdb63e2a61a79a6f955b7207780c80ff7ef419
#    container_name: book_store_front
#    depends_on:
#      - app
#    networks:
#      - my_network
#    build:
#      context: C:\Users\goose\IdeaProjects\OOP\frontbookstore  # Папка, где находится Dockerfile
#      dockerfile: Dockerfile  # Имя Dockerfile, если он называется по-другому
#    ports:
#      - "8080:5000"
#    volumes:
#      - C:\\Users\\goose\\IdeaProjects\\OOP\\frontbookstore\\nginx\\nginx.conf:/etc/nginx/nginx.conf  # Путь к файлу конфигурации

networks:
  my_network:
